baseURL = "http://www.joriseekhout.com/"
languageCode = "en-us"
title = "Joris Eekhout"
paginate = 5
pluralizelisttitles = false
googleAnalytics = "UA-59890904-1"

[blackfriday]
    hrefTargetBlank = true

[params]
    author = "Joris Eekhout"
    description = "I am a postdoctoral researcher at the Soil and Water Conservation Research Group in CEBAS-CSIC (Murcia, Spain). I focusses on the impact of climate change and landuse change on hydrology and soil erosion in Mediterranean environments. On my personal website you can find my research output (publications, presentations and projects) and outreach activities (a blog and videos)."
    publication_types = [
        'Uncategorized',  # 0
        'Journal',  # 1
        'Work in progress',  # 2
        'Conference proceedings',  # 3
        'Thesis',  # 4
        'Reports',  # 5
        'Popular scientific article',  # 6
    ]
    presentation_types = [
        'Oral presentation',  # 1
        'Poster presentation'  # 2
    ]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3

[[menu.main]]
    name = "Presentations"
    url = "/presentations/"
    weight = 4

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5

[[menu.main]]
    name = "Videos"
    url = "/videos/"
    weight = 6

[[menu.main]]
    name = "About Me"
    url = "/about-me/"
    weight = 7



# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/


# Taxonomies.
[taxonomies]
    tag = "tags"
    category = "categories"
    publication_type = "publication_types"
